/*
 * This file is generated by jOOQ.
*/
package project.pilot.jooq.model.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;

import project.pilot.jooq.model.tables.CarAdvertise;


/**
 * 차량매물정보
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarAdvertiseRecord extends UpdatableRecordImpl<CarAdvertiseRecord> implements Record16<Integer, String, Integer, String, String, String, String, String, String, String, String, Date, Integer, Integer, Date, Date> {

    private static final long serialVersionUID = 1041329429;

    /**
     * Setter for <code>pilot.car_advertise.CAR_NO</code>. 차량번호
     */
    public void setCarNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.CAR_NO</code>. 차량번호
     */
    public Integer getCarNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pilot.car_advertise.DEALER_ID</code>. 딜러ID
     */
    public void setDealerId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.DEALER_ID</code>. 딜러ID
     */
    public String getDealerId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pilot.car_advertise.MAKER_NO</code>. 제조사번호
     */
    public void setMakerNo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.MAKER_NO</code>. 제조사번호
     */
    public Integer getMakerNo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>pilot.car_advertise.MODEL_NO</code>. 모델번호
     */
    public void setModelNo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.MODEL_NO</code>. 모델번호
     */
    public String getModelNo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pilot.car_advertise.DETAIL_MODEL_NO</code>. 상세모델번호
     */
    public void setDetailModelNo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.DETAIL_MODEL_NO</code>. 상세모델번호
     */
    public String getDetailModelNo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pilot.car_advertise.GRADE_NO</code>. 등급번호
     */
    public void setGradeNo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.GRADE_NO</code>. 등급번호
     */
    public String getGradeNo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pilot.car_advertise.DETAIL_GRADE_NO</code>. 상세등급번호
     */
    public void setDetailGradeNo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.DETAIL_GRADE_NO</code>. 상세등급번호
     */
    public String getDetailGradeNo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pilot.car_advertise.FUEL_CODE</code>. 연료코드
     */
    public void setFuelCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.FUEL_CODE</code>. 연료코드
     */
    public String getFuelCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>pilot.car_advertise.MISSION_CODE</code>. 미션코드
     */
    public void setMissionCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.MISSION_CODE</code>. 미션코드
     */
    public String getMissionCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>pilot.car_advertise.PLATE_NUMBER</code>. 등록번호
     */
    public void setPlateNumber(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.PLATE_NUMBER</code>. 등록번호
     */
    public String getPlateNumber() {
        return (String) get(9);
    }

    /**
     * Setter for <code>pilot.car_advertise.CAR_REG_YEAR</code>. 차량등록년도
     */
    public void setCarRegYear(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.CAR_REG_YEAR</code>. 차량등록년도
     */
    public String getCarRegYear() {
        return (String) get(10);
    }

    /**
     * Setter for <code>pilot.car_advertise.APPLY_DATE</code>. 최초등록일자
     */
    public void setApplyDate(Date value) {
        set(11, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.APPLY_DATE</code>. 최초등록일자
     */
    public Date getApplyDate() {
        return (Date) get(11);
    }

    /**
     * Setter for <code>pilot.car_advertise.DISTANCE_AMOUNT</code>. 주행거리
     */
    public void setDistanceAmount(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.DISTANCE_AMOUNT</code>. 주행거리
     */
    public Integer getDistanceAmount() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>pilot.car_advertise.SALE_AMOUNT</code>. 차량판매가
     */
    public void setSaleAmount(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.SALE_AMOUNT</code>. 차량판매가
     */
    public Integer getSaleAmount() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>pilot.car_advertise.CREATE_DATE</code>. 등록일자
     */
    public void setCreateDate(Date value) {
        set(14, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.CREATE_DATE</code>. 등록일자
     */
    public Date getCreateDate() {
        return (Date) get(14);
    }

    /**
     * Setter for <code>pilot.car_advertise.LAST_UPDATE_DATE</code>. 최종수정일자
     */
    public void setLastUpdateDate(Date value) {
        set(15, value);
    }

    /**
     * Getter for <code>pilot.car_advertise.LAST_UPDATE_DATE</code>. 최종수정일자
     */
    public Date getLastUpdateDate() {
        return (Date) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, String, Integer, String, String, String, String, String, String, String, String, Date, Integer, Integer, Date, Date> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, String, Integer, String, String, String, String, String, String, String, String, Date, Integer, Integer, Date, Date> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CarAdvertise.CAR_ADVERTISE.CAR_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CarAdvertise.CAR_ADVERTISE.DEALER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CarAdvertise.CAR_ADVERTISE.MAKER_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CarAdvertise.CAR_ADVERTISE.MODEL_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CarAdvertise.CAR_ADVERTISE.DETAIL_MODEL_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CarAdvertise.CAR_ADVERTISE.GRADE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CarAdvertise.CAR_ADVERTISE.DETAIL_GRADE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return CarAdvertise.CAR_ADVERTISE.FUEL_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return CarAdvertise.CAR_ADVERTISE.MISSION_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return CarAdvertise.CAR_ADVERTISE.PLATE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return CarAdvertise.CAR_ADVERTISE.CAR_REG_YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field12() {
        return CarAdvertise.CAR_ADVERTISE.APPLY_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return CarAdvertise.CAR_ADVERTISE.DISTANCE_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return CarAdvertise.CAR_ADVERTISE.SALE_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field15() {
        return CarAdvertise.CAR_ADVERTISE.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field16() {
        return CarAdvertise.CAR_ADVERTISE.LAST_UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCarNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDealerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getMakerNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getModelNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDetailModelNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getGradeNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDetailGradeNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getFuelCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getMissionCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getPlateNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCarRegYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component12() {
        return getApplyDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getDistanceAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getSaleAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component15() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component16() {
        return getLastUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCarNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDealerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMakerNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getModelNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDetailModelNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getGradeNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDetailGradeNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getFuelCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getMissionCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getPlateNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCarRegYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value12() {
        return getApplyDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getDistanceAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getSaleAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value15() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value16() {
        return getLastUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value1(Integer value) {
        setCarNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value2(String value) {
        setDealerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value3(Integer value) {
        setMakerNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value4(String value) {
        setModelNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value5(String value) {
        setDetailModelNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value6(String value) {
        setGradeNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value7(String value) {
        setDetailGradeNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value8(String value) {
        setFuelCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value9(String value) {
        setMissionCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value10(String value) {
        setPlateNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value11(String value) {
        setCarRegYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value12(Date value) {
        setApplyDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value13(Integer value) {
        setDistanceAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value14(Integer value) {
        setSaleAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value15(Date value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord value16(Date value) {
        setLastUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertiseRecord values(Integer value1, String value2, Integer value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, Date value12, Integer value13, Integer value14, Date value15, Date value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CarAdvertiseRecord
     */
    public CarAdvertiseRecord() {
        super(CarAdvertise.CAR_ADVERTISE);
    }

    /**
     * Create a detached, initialised CarAdvertiseRecord
     */
    public CarAdvertiseRecord(Integer carNo, String dealerId, Integer makerNo, String modelNo, String detailModelNo, String gradeNo, String detailGradeNo, String fuelCode, String missionCode, String plateNumber, String carRegYear, Date applyDate, Integer distanceAmount, Integer saleAmount, Date createDate, Date lastUpdateDate) {
        super(CarAdvertise.CAR_ADVERTISE);

        set(0, carNo);
        set(1, dealerId);
        set(2, makerNo);
        set(3, modelNo);
        set(4, detailModelNo);
        set(5, gradeNo);
        set(6, detailGradeNo);
        set(7, fuelCode);
        set(8, missionCode);
        set(9, plateNumber);
        set(10, carRegYear);
        set(11, applyDate);
        set(12, distanceAmount);
        set(13, saleAmount);
        set(14, createDate);
        set(15, lastUpdateDate);
    }
}
