/*
 * This file is generated by jOOQ.
*/
package project.pilot.jooq.model;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;

import project.pilot.jooq.model.tables.CarAdvertise;
import project.pilot.jooq.model.tables.Dealer;


/**
 * A class modelling indexes of tables of the <code>pilot</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CAR_ADVERTISE_PRIMARY = Indexes0.CAR_ADVERTISE_PRIMARY;
    public static final Index DEALER_PRIMARY = Indexes0.DEALER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index CAR_ADVERTISE_PRIMARY = createIndex("PRIMARY", CarAdvertise.CAR_ADVERTISE, new OrderField[] { CarAdvertise.CAR_ADVERTISE.CAR_NO }, true);
        public static Index DEALER_PRIMARY = createIndex("PRIMARY", Dealer.DEALER, new OrderField[] { Dealer.DEALER.DEALER_ID }, true);
    }
}
