/*
 * This file is generated by jOOQ.
*/
package project.pilot.jooq.model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import project.pilot.jooq.model.tables.CarAdvertise;
import project.pilot.jooq.model.tables.Dealer;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pilot extends SchemaImpl {

    private static final long serialVersionUID = -660930511;

    /**
     * The reference instance of <code>pilot</code>
     */
    public static final Pilot PILOT = new Pilot();

    /**
     * 차량매물정보
     */
    public final CarAdvertise CAR_ADVERTISE = project.pilot.jooq.model.tables.CarAdvertise.CAR_ADVERTISE;

    /**
     * 딜러
     */
    public final Dealer DEALER = project.pilot.jooq.model.tables.Dealer.DEALER;

    /**
     * No further instances allowed
     */
    private Pilot() {
        super("pilot", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            CarAdvertise.CAR_ADVERTISE,
            Dealer.DEALER);
    }
}
