/*
 * This file is generated by jOOQ.
*/
package project.pilot.jooq.model;


import javax.annotation.Generated;

import project.pilot.jooq.model.tables.CarAdvertise;
import project.pilot.jooq.model.tables.Dealer;


/**
 * Convenience access to all tables in pilot
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 차량매물정보
     */
    public static final CarAdvertise CAR_ADVERTISE = project.pilot.jooq.model.tables.CarAdvertise.CAR_ADVERTISE;

    /**
     * 딜러
     */
    public static final Dealer DEALER = project.pilot.jooq.model.tables.Dealer.DEALER;
}
