/*
 * This file is generated by jOOQ.
*/
package project.pilot.jooq.model.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import project.pilot.jooq.model.Indexes;
import project.pilot.jooq.model.Keys;
import project.pilot.jooq.model.Pilot;
import project.pilot.jooq.model.tables.records.CarAdvertiseRecord;


/**
 * 차량매물정보
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarAdvertise extends TableImpl<CarAdvertiseRecord> {

    private static final long serialVersionUID = -1442653374;

    /**
     * The reference instance of <code>pilot.car_advertise</code>
     */
    public static final CarAdvertise CAR_ADVERTISE = new CarAdvertise();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CarAdvertiseRecord> getRecordType() {
        return CarAdvertiseRecord.class;
    }

    /**
     * The column <code>pilot.car_advertise.CAR_NO</code>. 차량번호
     */
    public final TableField<CarAdvertiseRecord, Integer> CAR_NO = createField("CAR_NO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "차량번호");

    /**
     * The column <code>pilot.car_advertise.DEALER_ID</code>. 딜러ID
     */
    public final TableField<CarAdvertiseRecord, String> DEALER_ID = createField("DEALER_ID", org.jooq.impl.SQLDataType.VARCHAR(100).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "딜러ID");

    /**
     * The column <code>pilot.car_advertise.MAKER_NO</code>. 제조사번호
     */
    public final TableField<CarAdvertiseRecord, Integer> MAKER_NO = createField("MAKER_NO", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "제조사번호");

    /**
     * The column <code>pilot.car_advertise.MODEL_NO</code>. 모델번호
     */
    public final TableField<CarAdvertiseRecord, String> MODEL_NO = createField("MODEL_NO", org.jooq.impl.SQLDataType.VARCHAR(10).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "모델번호");

    /**
     * The column <code>pilot.car_advertise.DETAIL_MODEL_NO</code>. 상세모델번호
     */
    public final TableField<CarAdvertiseRecord, String> DETAIL_MODEL_NO = createField("DETAIL_MODEL_NO", org.jooq.impl.SQLDataType.VARCHAR(10).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "상세모델번호");

    /**
     * The column <code>pilot.car_advertise.GRADE_NO</code>. 등급번호
     */
    public final TableField<CarAdvertiseRecord, String> GRADE_NO = createField("GRADE_NO", org.jooq.impl.SQLDataType.VARCHAR(10).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "등급번호");

    /**
     * The column <code>pilot.car_advertise.DETAIL_GRADE_NO</code>. 상세등급번호
     */
    public final TableField<CarAdvertiseRecord, String> DETAIL_GRADE_NO = createField("DETAIL_GRADE_NO", org.jooq.impl.SQLDataType.VARCHAR(10).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "상세등급번호");

    /**
     * The column <code>pilot.car_advertise.FUEL_CODE</code>. 연료코드
     */
    public final TableField<CarAdvertiseRecord, String> FUEL_CODE = createField("FUEL_CODE", org.jooq.impl.SQLDataType.VARCHAR(10).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "연료코드");

    /**
     * The column <code>pilot.car_advertise.MISSION_CODE</code>. 미션코드
     */
    public final TableField<CarAdvertiseRecord, String> MISSION_CODE = createField("MISSION_CODE", org.jooq.impl.SQLDataType.VARCHAR(10).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "미션코드");

    /**
     * The column <code>pilot.car_advertise.PLATE_NUMBER</code>. 등록번호
     */
    public final TableField<CarAdvertiseRecord, String> PLATE_NUMBER = createField("PLATE_NUMBER", org.jooq.impl.SQLDataType.VARCHAR(10).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "등록번호");

    /**
     * The column <code>pilot.car_advertise.CAR_REG_YEAR</code>. 차량등록년도
     */
    public final TableField<CarAdvertiseRecord, String> CAR_REG_YEAR = createField("CAR_REG_YEAR", org.jooq.impl.SQLDataType.CHAR(4).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.CHAR)), this, "차량등록년도");

    /**
     * The column <code>pilot.car_advertise.APPLY_DATE</code>. 최초등록일자
     */
    public final TableField<CarAdvertiseRecord, Date> APPLY_DATE = createField("APPLY_DATE", org.jooq.impl.SQLDataType.DATE.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.DATE)), this, "최초등록일자");

    /**
     * The column <code>pilot.car_advertise.DISTANCE_AMOUNT</code>. 주행거리
     */
    public final TableField<CarAdvertiseRecord, Integer> DISTANCE_AMOUNT = createField("DISTANCE_AMOUNT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "주행거리");

    /**
     * The column <code>pilot.car_advertise.SALE_AMOUNT</code>. 차량판매가
     */
    public final TableField<CarAdvertiseRecord, Integer> SALE_AMOUNT = createField("SALE_AMOUNT", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "차량판매가");

    /**
     * The column <code>pilot.car_advertise.CREATE_DATE</code>. 등록일자
     */
    public final TableField<CarAdvertiseRecord, Date> CREATE_DATE = createField("CREATE_DATE", org.jooq.impl.SQLDataType.DATE.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.DATE)), this, "등록일자");

    /**
     * The column <code>pilot.car_advertise.LAST_UPDATE_DATE</code>. 최종수정일자
     */
    public final TableField<CarAdvertiseRecord, Date> LAST_UPDATE_DATE = createField("LAST_UPDATE_DATE", org.jooq.impl.SQLDataType.DATE.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.DATE)), this, "최종수정일자");

    /**
     * Create a <code>pilot.car_advertise</code> table reference
     */
    public CarAdvertise() {
        this(DSL.name("car_advertise"), null);
    }

    /**
     * Create an aliased <code>pilot.car_advertise</code> table reference
     */
    public CarAdvertise(String alias) {
        this(DSL.name(alias), CAR_ADVERTISE);
    }

    /**
     * Create an aliased <code>pilot.car_advertise</code> table reference
     */
    public CarAdvertise(Name alias) {
        this(alias, CAR_ADVERTISE);
    }

    private CarAdvertise(Name alias, Table<CarAdvertiseRecord> aliased) {
        this(alias, aliased, null);
    }

    private CarAdvertise(Name alias, Table<CarAdvertiseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "차량매물정보");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pilot.PILOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CAR_ADVERTISE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CarAdvertiseRecord> getPrimaryKey() {
        return Keys.KEY_CAR_ADVERTISE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CarAdvertiseRecord>> getKeys() {
        return Arrays.<UniqueKey<CarAdvertiseRecord>>asList(Keys.KEY_CAR_ADVERTISE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertise as(String alias) {
        return new CarAdvertise(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarAdvertise as(Name alias) {
        return new CarAdvertise(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CarAdvertise rename(String name) {
        return new CarAdvertise(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CarAdvertise rename(Name name) {
        return new CarAdvertise(name, null);
    }
}
